name: "Pull Request Docs Check"
on:
  push:
     branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        pip install sphinx_rtd_theme
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
