# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: reed_api

on:
  push:
    branches: [ "master" ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme
        
    - name: make the sphnx docs
      run: |
        make -C docs clean
        make -C docs html
    
